name: node-ci

on:
  push:
    paths-ignore:
      - "contracts/**"
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "contracts/**"
      - "docs/**"
      - "*.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          
      # Clean installation of dependencies using the package lock
      - run: npm ci
      
      # Executes the workspaces build steps
      - run: npm run build
      
      - run: npm run test --if-present
      
      - run: npm run lint --if-present